build :
	python setup.py build_ext --inplace

update :
	jupyter nbconvert --to script Problem1.ipynb
	jupyter nbconvert --to script Problem2.ipynb
	jupyter nbconvert --to script Problem31.ipynb
	jupyter nbconvert --to script Problem32.ipynb
	
run :
	python Problem1.py
	python Problem2.py
	python Problem31.py
	python Problem32.py
